name: "mvn-deploy "
description: "Deploy to github packages"
inputs:
  directory:
    description: "Directory"
    required: true
  github_workspace:
    description: "Github workspace"
    required: true  
  github_token:
    description: "Github Token"
    required: true  
runs:
  using: "composite"
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: "21"
        distribution: "adopt"
        cache: "maven"
    - name: Release
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: mvn deploy -s .mvn/settings.xml
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }} 
